development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  username: duncanmorrison

production:
  adapter: postgresql
  encoding: unicode
  database: dbimpkgan8ao50
  username: ykywuglfjybhwf
  password: d3d41b2ee3731def86a8c12a483606ace0d5016cbe25c7ec0048d1b1479941d5

test:
  adapter: postgresql
  encoding: unicode
  database: chitter_test
  username: duncanmorrison